/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as VoipRouteImport } from './routes/voip'
import { Route as ApiConsultRouteImport } from './routes/api/consult'
import { Route as ConsultContinueRouteImport } from './routes/consult_.continue'
import { Route as DentalItOntarioRouteImport } from './routes/dental-it.ontario'
import { Route as FleetOperationsOntarioRouteImport } from './routes/fleet-operations.ontario'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const VoipRoute = VoipRouteImport.update({
  id: '/voip',
  path: '/voip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultRoute = ApiConsultRouteImport.update({
  id: '/api/consult',
  path: '/api/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultContinueRoute = ConsultContinueRouteImport.update({
  id: '/consult_/continue',
  path: '/consult/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalItOntarioRoute = DentalItOntarioRouteImport.update({
  id: '/dental-it/ontario',
  path: '/dental-it/ontario',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetOperationsOntarioRoute = FleetOperationsOntarioRouteImport.update({
  id: '/fleet-operations/ontario',
  path: '/fleet-operations/ontario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/consult': typeof ConsultRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hardware': typeof HardwareRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/security': typeof SecurityRoute
  '/service-areas': typeof ServiceAreasRoute
  '/software': typeof SoftwareRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/voip': typeof VoipRoute
  '/api/consult': typeof ApiConsultRoute
  '/consult/continue': typeof ConsultContinueRoute
  '/dental-it/ontario': typeof DentalItOntarioRoute
  '/fleet-operations/ontario': typeof FleetOperationsOntarioRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/consult': typeof ConsultRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hardware': typeof HardwareRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/security': typeof SecurityRoute
  '/service-areas': typeof ServiceAreasRoute
  '/software': typeof SoftwareRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/voip': typeof VoipRoute
  '/api/consult': typeof ApiConsultRoute
  '/consult/continue': typeof ConsultContinueRoute
  '/dental-it/ontario': typeof DentalItOntarioRoute
  '/fleet-operations/ontario': typeof FleetOperationsOntarioRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/consult': typeof ConsultRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hardware': typeof HardwareRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/security': typeof SecurityRoute
  '/service-areas': typeof ServiceAreasRoute
  '/software': typeof SoftwareRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/voip': typeof VoipRoute
  '/api/consult': typeof ApiConsultRoute
  '/consult_/continue': typeof ConsultContinueRoute
  '/dental-it/ontario': typeof DentalItOntarioRoute
  '/fleet-operations/ontario': typeof FleetOperationsOntarioRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/consult'
    | '/digital-marketing'
    | '/faq'
    | '/gallery'
    | '/hardware'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/security'
    | '/service-areas'
    | '/software'
    | '/support'
    | '/thank-you'
    | '/voip'
    | '/api/consult'
    | '/consult/continue'
    | '/dental-it/ontario'
    | '/fleet-operations/ontario'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/industries/'
    | '/insights/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/consult'
    | '/digital-marketing'
    | '/faq'
    | '/gallery'
    | '/hardware'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/security'
    | '/service-areas'
    | '/software'
    | '/support'
    | '/thank-you'
    | '/voip'
    | '/api/consult'
    | '/consult/continue'
    | '/dental-it/ontario'
    | '/fleet-operations/ontario'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/industries'
    | '/insights'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/consult'
    | '/digital-marketing'
    | '/faq'
    | '/gallery'
    | '/hardware'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/security'
    | '/service-areas'
    | '/software'
    | '/support'
    | '/thank-you'
    | '/voip'
    | '/api/consult'
    | '/consult_/continue'
    | '/dental-it/ontario'
    | '/fleet-operations/ontario'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/industries/'
    | '/insights/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ConsultRoute: typeof ConsultRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HardwareRoute: typeof HardwareRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  SecurityRoute: typeof SecurityRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  SoftwareRoute: typeof SoftwareRoute
  SupportRoute: typeof SupportRoute
  ThankYouRoute: typeof ThankYouRoute
  VoipRoute: typeof VoipRoute
  ApiConsultRoute: typeof ApiConsultRoute
  ConsultContinueRoute: typeof ConsultContinueRoute
  DentalItOntarioRoute: typeof DentalItOntarioRoute
  FleetOperationsOntarioRoute: typeof FleetOperationsOntarioRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voip': {
      id: '/voip'
      path: '/voip'
      fullPath: '/voip'
      preLoaderRoute: typeof VoipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consult': {
      id: '/api/consult'
      path: '/api/consult'
      fullPath: '/api/consult'
      preLoaderRoute: typeof ApiConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult_/continue': {
      id: '/consult_/continue'
      path: '/consult/continue'
      fullPath: '/consult/continue'
      preLoaderRoute: typeof ConsultContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-it/ontario': {
      id: '/dental-it/ontario'
      path: '/dental-it/ontario'
      fullPath: '/dental-it/ontario'
      preLoaderRoute: typeof DentalItOntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-operations/ontario': {
      id: '/fleet-operations/ontario'
      path: '/fleet-operations/ontario'
      fullPath: '/fleet-operations/ontario'
      preLoaderRoute: typeof FleetOperationsOntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ConsultRoute: ConsultRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HardwareRoute: HardwareRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  SecurityRoute: SecurityRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  SoftwareRoute: SoftwareRoute,
  SupportRoute: SupportRoute,
  ThankYouRoute: ThankYouRoute,
  VoipRoute: VoipRoute,
  ApiConsultRoute: ApiConsultRoute,
  ConsultContinueRoute: ConsultContinueRoute,
  DentalItOntarioRoute: DentalItOntarioRoute,
  FleetOperationsOntarioRoute: FleetOperationsOntarioRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
