/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R10SignsYourBusinessNeedsManagedItSupportRouteImport } from './routes/10-signs-your-business-needs-managed-it-support'
import { Route as R5BiggestBenefitsOfCloudBackupsRouteImport } from './routes/5-biggest-benefits-of-cloud-backups'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AccessibilityStatementRouteImport } from './routes/accessibility-statement'
import { Route as AiRouteImport } from './routes/ai'
import { Route as CloudServicesBramptonRouteImport } from './routes/cloud-services-brampton'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as CyberSecurityTipsForSmallBusinessesRouteImport } from './routes/cyber-security-tips-for-small-businesses'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as HowToChooseAManagedItServicesProviderRouteImport } from './routes/how-to-choose-a-managed-it-services-provider'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025RouteImport } from './routes/top-7-cyber-security-solutions-every-business-needs-in-2025'
import { Route as VoipRouteImport } from './routes/voip'
import { Route as ApiConsultRouteImport } from './routes/api/consult'
import { Route as ApiTicketRouteImport } from './routes/api/ticket'
import { Route as DentalItOntarioRouteImport } from './routes/dental-it.ontario'
import { Route as FleetOperationsOntarioRouteImport } from './routes/fleet-operations.ontario'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R10SignsYourBusinessNeedsManagedItSupportRoute =
  R10SignsYourBusinessNeedsManagedItSupportRouteImport.update({
    id: '/10-signs-your-business-needs-managed-it-support',
    path: '/10-signs-your-business-needs-managed-it-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const R5BiggestBenefitsOfCloudBackupsRoute =
  R5BiggestBenefitsOfCloudBackupsRouteImport.update({
    id: '/5-biggest-benefits-of-cloud-backups',
    path: '/5-biggest-benefits-of-cloud-backups',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityStatementRoute = AccessibilityStatementRouteImport.update({
  id: '/accessibility-statement',
  path: '/accessibility-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudServicesBramptonRoute = CloudServicesBramptonRouteImport.update({
  id: '/cloud-services-brampton',
  path: '/cloud-services-brampton',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberSecurityTipsForSmallBusinessesRoute =
  CyberSecurityTipsForSmallBusinessesRouteImport.update({
    id: '/cyber-security-tips-for-small-businesses',
    path: '/cyber-security-tips-for-small-businesses',
    getParentRoute: () => rootRouteImport,
  } as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToChooseAManagedItServicesProviderRoute =
  HowToChooseAManagedItServicesProviderRouteImport.update({
    id: '/how-to-choose-a-managed-it-services-provider',
    path: '/how-to-choose-a-managed-it-services-provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route =
  Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025RouteImport.update({
    id: '/top-7-cyber-security-solutions-every-business-needs-in-2025',
    path: '/top-7-cyber-security-solutions-every-business-needs-in-2025',
    getParentRoute: () => rootRouteImport,
  } as any)
const VoipRoute = VoipRouteImport.update({
  id: '/voip',
  path: '/voip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultRoute = ApiConsultRouteImport.update({
  id: '/api/consult',
  path: '/api/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketRoute = ApiTicketRouteImport.update({
  id: '/api/ticket',
  path: '/api/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const DentalItOntarioRoute = DentalItOntarioRouteImport.update({
  id: '/dental-it/ontario',
  path: '/dental-it/ontario',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetOperationsOntarioRoute = FleetOperationsOntarioRouteImport.update({
  id: '/fleet-operations/ontario',
  path: '/fleet-operations/ontario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/10-signs-your-business-needs-managed-it-support': typeof R10SignsYourBusinessNeedsManagedItSupportRoute
  '/5-biggest-benefits-of-cloud-backups': typeof R5BiggestBenefitsOfCloudBackupsRoute
  '/about-us': typeof AboutUsRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/ai': typeof AiRoute
  '/cloud-services-brampton': typeof CloudServicesBramptonRoute
  '/consult': typeof ConsultRoute
  '/cyber-security-tips-for-small-businesses': typeof CyberSecurityTipsForSmallBusinessesRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hardware': typeof HardwareRoute
  '/how-to-choose-a-managed-it-services-provider': typeof HowToChooseAManagedItServicesProviderRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/security': typeof SecurityRoute
  '/service-areas': typeof ServiceAreasRoute
  '/software': typeof SoftwareRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/ticket': typeof TicketRoute
  '/top-7-cyber-security-solutions-every-business-needs-in-2025': typeof Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route
  '/voip': typeof VoipRoute
  '/api/consult': typeof ApiConsultRoute
  '/api/ticket': typeof ApiTicketRoute
  '/dental-it/ontario': typeof DentalItOntarioRoute
  '/fleet-operations/ontario': typeof FleetOperationsOntarioRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/10-signs-your-business-needs-managed-it-support': typeof R10SignsYourBusinessNeedsManagedItSupportRoute
  '/5-biggest-benefits-of-cloud-backups': typeof R5BiggestBenefitsOfCloudBackupsRoute
  '/about-us': typeof AboutUsRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/ai': typeof AiRoute
  '/cloud-services-brampton': typeof CloudServicesBramptonRoute
  '/consult': typeof ConsultRoute
  '/cyber-security-tips-for-small-businesses': typeof CyberSecurityTipsForSmallBusinessesRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hardware': typeof HardwareRoute
  '/how-to-choose-a-managed-it-services-provider': typeof HowToChooseAManagedItServicesProviderRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/security': typeof SecurityRoute
  '/service-areas': typeof ServiceAreasRoute
  '/software': typeof SoftwareRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/ticket': typeof TicketRoute
  '/top-7-cyber-security-solutions-every-business-needs-in-2025': typeof Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route
  '/voip': typeof VoipRoute
  '/api/consult': typeof ApiConsultRoute
  '/api/ticket': typeof ApiTicketRoute
  '/dental-it/ontario': typeof DentalItOntarioRoute
  '/fleet-operations/ontario': typeof FleetOperationsOntarioRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/10-signs-your-business-needs-managed-it-support': typeof R10SignsYourBusinessNeedsManagedItSupportRoute
  '/5-biggest-benefits-of-cloud-backups': typeof R5BiggestBenefitsOfCloudBackupsRoute
  '/about-us': typeof AboutUsRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/ai': typeof AiRoute
  '/cloud-services-brampton': typeof CloudServicesBramptonRoute
  '/consult': typeof ConsultRoute
  '/cyber-security-tips-for-small-businesses': typeof CyberSecurityTipsForSmallBusinessesRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/hardware': typeof HardwareRoute
  '/how-to-choose-a-managed-it-services-provider': typeof HowToChooseAManagedItServicesProviderRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/security': typeof SecurityRoute
  '/service-areas': typeof ServiceAreasRoute
  '/software': typeof SoftwareRoute
  '/solutions': typeof SolutionsRoute
  '/support': typeof SupportRoute
  '/thank-you': typeof ThankYouRoute
  '/ticket': typeof TicketRoute
  '/top-7-cyber-security-solutions-every-business-needs-in-2025': typeof Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route
  '/voip': typeof VoipRoute
  '/api/consult': typeof ApiConsultRoute
  '/api/ticket': typeof ApiTicketRoute
  '/dental-it/ontario': typeof DentalItOntarioRoute
  '/fleet-operations/ontario': typeof FleetOperationsOntarioRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/10-signs-your-business-needs-managed-it-support'
    | '/5-biggest-benefits-of-cloud-backups'
    | '/about-us'
    | '/accessibility-statement'
    | '/ai'
    | '/cloud-services-brampton'
    | '/consult'
    | '/cyber-security-tips-for-small-businesses'
    | '/digital-marketing'
    | '/faq'
    | '/gallery'
    | '/hardware'
    | '/how-to-choose-a-managed-it-services-provider'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/security'
    | '/service-areas'
    | '/software'
    | '/solutions'
    | '/support'
    | '/thank-you'
    | '/ticket'
    | '/top-7-cyber-security-solutions-every-business-needs-in-2025'
    | '/voip'
    | '/api/consult'
    | '/api/ticket'
    | '/dental-it/ontario'
    | '/fleet-operations/ontario'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/industries/'
    | '/insights/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/10-signs-your-business-needs-managed-it-support'
    | '/5-biggest-benefits-of-cloud-backups'
    | '/about-us'
    | '/accessibility-statement'
    | '/ai'
    | '/cloud-services-brampton'
    | '/consult'
    | '/cyber-security-tips-for-small-businesses'
    | '/digital-marketing'
    | '/faq'
    | '/gallery'
    | '/hardware'
    | '/how-to-choose-a-managed-it-services-provider'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/security'
    | '/service-areas'
    | '/software'
    | '/solutions'
    | '/support'
    | '/thank-you'
    | '/ticket'
    | '/top-7-cyber-security-solutions-every-business-needs-in-2025'
    | '/voip'
    | '/api/consult'
    | '/api/ticket'
    | '/dental-it/ontario'
    | '/fleet-operations/ontario'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/industries'
    | '/insights'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/10-signs-your-business-needs-managed-it-support'
    | '/5-biggest-benefits-of-cloud-backups'
    | '/about-us'
    | '/accessibility-statement'
    | '/ai'
    | '/cloud-services-brampton'
    | '/consult'
    | '/cyber-security-tips-for-small-businesses'
    | '/digital-marketing'
    | '/faq'
    | '/gallery'
    | '/hardware'
    | '/how-to-choose-a-managed-it-services-provider'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/security'
    | '/service-areas'
    | '/software'
    | '/solutions'
    | '/support'
    | '/thank-you'
    | '/ticket'
    | '/top-7-cyber-security-solutions-every-business-needs-in-2025'
    | '/voip'
    | '/api/consult'
    | '/api/ticket'
    | '/dental-it/ontario'
    | '/fleet-operations/ontario'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/industries/'
    | '/insights/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R10SignsYourBusinessNeedsManagedItSupportRoute: typeof R10SignsYourBusinessNeedsManagedItSupportRoute
  R5BiggestBenefitsOfCloudBackupsRoute: typeof R5BiggestBenefitsOfCloudBackupsRoute
  AboutUsRoute: typeof AboutUsRoute
  AccessibilityStatementRoute: typeof AccessibilityStatementRoute
  AiRoute: typeof AiRoute
  CloudServicesBramptonRoute: typeof CloudServicesBramptonRoute
  ConsultRoute: typeof ConsultRoute
  CyberSecurityTipsForSmallBusinessesRoute: typeof CyberSecurityTipsForSmallBusinessesRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HardwareRoute: typeof HardwareRoute
  HowToChooseAManagedItServicesProviderRoute: typeof HowToChooseAManagedItServicesProviderRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  SecurityRoute: typeof SecurityRoute
  ServiceAreasRoute: typeof ServiceAreasRoute
  SoftwareRoute: typeof SoftwareRoute
  SolutionsRoute: typeof SolutionsRoute
  SupportRoute: typeof SupportRoute
  ThankYouRoute: typeof ThankYouRoute
  TicketRoute: typeof TicketRoute
  Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route: typeof Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route
  VoipRoute: typeof VoipRoute
  ApiConsultRoute: typeof ApiConsultRoute
  ApiTicketRoute: typeof ApiTicketRoute
  DentalItOntarioRoute: typeof DentalItOntarioRoute
  FleetOperationsOntarioRoute: typeof FleetOperationsOntarioRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10-signs-your-business-needs-managed-it-support': {
      id: '/10-signs-your-business-needs-managed-it-support'
      path: '/10-signs-your-business-needs-managed-it-support'
      fullPath: '/10-signs-your-business-needs-managed-it-support'
      preLoaderRoute: typeof R10SignsYourBusinessNeedsManagedItSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5-biggest-benefits-of-cloud-backups': {
      id: '/5-biggest-benefits-of-cloud-backups'
      path: '/5-biggest-benefits-of-cloud-backups'
      fullPath: '/5-biggest-benefits-of-cloud-backups'
      preLoaderRoute: typeof R5BiggestBenefitsOfCloudBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-statement': {
      id: '/accessibility-statement'
      path: '/accessibility-statement'
      fullPath: '/accessibility-statement'
      preLoaderRoute: typeof AccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-services-brampton': {
      id: '/cloud-services-brampton'
      path: '/cloud-services-brampton'
      fullPath: '/cloud-services-brampton'
      preLoaderRoute: typeof CloudServicesBramptonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-security-tips-for-small-businesses': {
      id: '/cyber-security-tips-for-small-businesses'
      path: '/cyber-security-tips-for-small-businesses'
      fullPath: '/cyber-security-tips-for-small-businesses'
      preLoaderRoute: typeof CyberSecurityTipsForSmallBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-choose-a-managed-it-services-provider': {
      id: '/how-to-choose-a-managed-it-services-provider'
      path: '/how-to-choose-a-managed-it-services-provider'
      fullPath: '/how-to-choose-a-managed-it-services-provider'
      preLoaderRoute: typeof HowToChooseAManagedItServicesProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-7-cyber-security-solutions-every-business-needs-in-2025': {
      id: '/top-7-cyber-security-solutions-every-business-needs-in-2025'
      path: '/top-7-cyber-security-solutions-every-business-needs-in-2025'
      fullPath: '/top-7-cyber-security-solutions-every-business-needs-in-2025'
      preLoaderRoute: typeof Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voip': {
      id: '/voip'
      path: '/voip'
      fullPath: '/voip'
      preLoaderRoute: typeof VoipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consult': {
      id: '/api/consult'
      path: '/api/consult'
      fullPath: '/api/consult'
      preLoaderRoute: typeof ApiConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ticket': {
      id: '/api/ticket'
      path: '/api/ticket'
      fullPath: '/api/ticket'
      preLoaderRoute: typeof ApiTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dental-it/ontario': {
      id: '/dental-it/ontario'
      path: '/dental-it/ontario'
      fullPath: '/dental-it/ontario'
      preLoaderRoute: typeof DentalItOntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-operations/ontario': {
      id: '/fleet-operations/ontario'
      path: '/fleet-operations/ontario'
      fullPath: '/fleet-operations/ontario'
      preLoaderRoute: typeof FleetOperationsOntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R10SignsYourBusinessNeedsManagedItSupportRoute:
    R10SignsYourBusinessNeedsManagedItSupportRoute,
  R5BiggestBenefitsOfCloudBackupsRoute: R5BiggestBenefitsOfCloudBackupsRoute,
  AboutUsRoute: AboutUsRoute,
  AccessibilityStatementRoute: AccessibilityStatementRoute,
  AiRoute: AiRoute,
  CloudServicesBramptonRoute: CloudServicesBramptonRoute,
  ConsultRoute: ConsultRoute,
  CyberSecurityTipsForSmallBusinessesRoute:
    CyberSecurityTipsForSmallBusinessesRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HardwareRoute: HardwareRoute,
  HowToChooseAManagedItServicesProviderRoute:
    HowToChooseAManagedItServicesProviderRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  SecurityRoute: SecurityRoute,
  ServiceAreasRoute: ServiceAreasRoute,
  SoftwareRoute: SoftwareRoute,
  SolutionsRoute: SolutionsRoute,
  SupportRoute: SupportRoute,
  ThankYouRoute: ThankYouRoute,
  TicketRoute: TicketRoute,
  Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route:
    Top7CyberSecuritySolutionsEveryBusinessNeedsIn2025Route,
  VoipRoute: VoipRoute,
  ApiConsultRoute: ApiConsultRoute,
  ApiTicketRoute: ApiTicketRoute,
  DentalItOntarioRoute: DentalItOntarioRoute,
  FleetOperationsOntarioRoute: FleetOperationsOntarioRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
